SELECT DISTINCT *
FROM Sales.Customers
ORDER BY custid ASC
OFFSET 0 ROWS FETCH FIRST 10 ROWS ONLY;

SELECT DISTINCT *
FROM Sales.Customers
ORDER BY custid ASC
OFFSET 10 ROWS FETCH FIRST 10 ROWS ONLY;

SELECT DISTINCT *
FROM Sales.Customers
ORDER BY custid ASC
OFFSET 20 ROWS FETCH FIRST 10 ROWS ONLY;

--SELECT DISTINCT TOP(30) * FROM Sales.Customers ORDER BY custid ASC;