-- Module 18
-- Create a table
USE tempdb;
GO
CREATE TABLE TRANTEST (ID int);
GO
-- INSERT INTO TABLE  - without transaction
INSERT INTO TRANTEST VALUES (1);
GO

SELECT * FROM TRANTEST;
GO

-- Start transaction
BEGIN TRAN

-- Add a new row
INSERT INTO TRANTEST VALUES (2);

-- Review table
SELECT * FROM TRANTEST;
  
-- Rollback transaction
ROLLBACK TRAN;

-- Verify transaction rolled back
SELECT * FROM TRANTEST;

-- Start new transaction
BEGIN TRAN;

-- Add a new row
INSERT INTO TRANTEST VALUES (3);

-- Review table
SELECT * FROM TRANTEST;

COMMIT TRAN;
GO
 -- Review table
SELECT * FROM TRANTEST;

-- Try/Catch

	SELECT XACT_STATE() AS XACT_STATE0;
	BEGIN TRY
		BEGIN TRAN
		SELECT XACT_STATE() AS XACT_STATE1;
		INSERT INTO TRANTEST VALUES (4);
		SELECT XACT_STATE() AS XACT_STATE2;
		INSERT INTO TRANTEST VALUES ('A');
		INSERT INTO TRANTEST VALUES (5);
		COMMIT TRAN;
	END TRY
	BEGIN CATCH
	    SELECT 'GOT HERE';
		SELECT XACT_STATE() AS XACT_STATE3;
		SELECT * FROM TRANTEST;
		ROLLBACK TRAN;
	END CATCH
	SELECT * FROM TRANTEST;

-- Auto Rollback doesn't happen with XACT_ABORT OFF (Default)
SET XACT_ABORT OFF;
BEGIN TRAN
INSERT INTO TRANTEST VALUES (5);
SELECT 1/0;
COMMIT TRAN;
SELECT * FROM TRANTEST; 

-- Auto Rollback does happen with XACT_ABORT ON  
SET XACT_ABORT ON;
BEGIN TRAN
INSERT INTO TRANTEST VALUES (6);
SELECT 1/0;
SELECT 'GOT HERE'
COMMIT TRAN;

-- What is around now
SELECT * FROM TRANTEST;

 

-- Clean up 
DROP TABLE TRANTEST;

